

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Addresses" (
    "address_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "street" "text" NOT NULL,
    "city" "text" NOT NULL,
    "state_province" "text" NOT NULL,
    "zip_postal" "text"
);


ALTER TABLE "public"."Addresses" OWNER TO "postgres";


ALTER TABLE "public"."Addresses" ALTER COLUMN "address_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Addresses_address_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."BleacherEvents" (
    "bleacher_event_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "bleacher_id" bigint NOT NULL,
    "event_id" bigint NOT NULL,
    "setup_text" "text",
    "setup_confirmed" boolean DEFAULT false NOT NULL,
    "teardown_text" "text",
    "teardown_confirmed" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."BleacherEvents" OWNER TO "postgres";


ALTER TABLE "public"."BleacherEvents" ALTER COLUMN "bleacher_event_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."BleacherEvents_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."BleacherUsers" (
    "bleacher_user_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" bigint NOT NULL,
    "bleacher_id" bigint NOT NULL,
    "season" "text" NOT NULL
);


ALTER TABLE "public"."BleacherUsers" OWNER TO "postgres";


ALTER TABLE "public"."BleacherUsers" ALTER COLUMN "bleacher_user_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."BleacherUsers_bleacher_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Bleachers" (
    "bleacher_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "bleacher_number" smallint NOT NULL,
    "home_base_id" bigint NOT NULL,
    "winter_home_base_id" bigint NOT NULL,
    "bleacher_rows" smallint NOT NULL,
    "bleacher_seats" smallint NOT NULL,
    "created_by" "uuid",
    "updated_at" timestamp without time zone,
    "updated_by" "uuid",
    "linxup_device_id" "text"
);

ALTER TABLE ONLY "public"."Bleachers" REPLICA IDENTITY FULL;


ALTER TABLE "public"."Bleachers" OWNER TO "postgres";


ALTER TABLE "public"."Bleachers" ALTER COLUMN "bleacher_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Bleachers_bleacher_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Blocks" (
    "block_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "bleacher_id" bigint,
    "text" "text",
    "date" "date"
);


ALTER TABLE "public"."Blocks" OWNER TO "postgres";


ALTER TABLE "public"."Blocks" ALTER COLUMN "block_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Blocks_block_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Drivers" (
    "driver_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" bigint NOT NULL,
    "tax" smallint DEFAULT '0'::smallint NOT NULL,
    "pay_rate_cents" smallint DEFAULT '0'::smallint NOT NULL,
    "pay_currency" "text" DEFAULT 'CAD'::"text" NOT NULL,
    "pay_per_unit" "text" DEFAULT 'KM'::"text" NOT NULL
);


ALTER TABLE "public"."Drivers" OWNER TO "postgres";


ALTER TABLE "public"."Drivers" ALTER COLUMN "driver_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Drivers_driver_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Events" (
    "event_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event_name" "text" NOT NULL,
    "setup_start" "date",
    "event_start" "date" NOT NULL,
    "event_end" "date" NOT NULL,
    "teardown_end" "date",
    "address_id" bigint NOT NULL,
    "total_seats" integer,
    "seven_row" smallint,
    "ten_row" smallint,
    "fifteen_row" smallint,
    "lenient" boolean NOT NULL,
    "booked" boolean DEFAULT false NOT NULL,
    "notes" "text",
    "must_be_clean" boolean DEFAULT false NOT NULL,
    "hsl_hue" smallint,
    "goodshuffle_url" "text",
    "created_by_user_id" bigint
);


ALTER TABLE "public"."Events" OWNER TO "postgres";


ALTER TABLE "public"."Events" ALTER COLUMN "event_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."HomeBases" (
    "home_base_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "home_base_name" "text" NOT NULL
);


ALTER TABLE "public"."HomeBases" OWNER TO "postgres";


ALTER TABLE "public"."HomeBases" ALTER COLUMN "home_base_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."HomeBases_home_base_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."TaskStatuses" (
    "task_status_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "label" "text" NOT NULL,
    "hex" "text" NOT NULL
);


ALTER TABLE "public"."TaskStatuses" OWNER TO "postgres";


ALTER TABLE "public"."TaskStatuses" ALTER COLUMN "task_status_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TaskStatuses_task_status_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."TaskTypes" (
    "task_type_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "label" "text" NOT NULL
);


ALTER TABLE "public"."TaskTypes" OWNER TO "postgres";


ALTER TABLE "public"."TaskTypes" ALTER COLUMN "task_type_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TaskTypes_task_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Tasks" (
    "task_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "created_by_user_id" bigint NOT NULL,
    "task_type_id" bigint NOT NULL,
    "task_status_id" bigint NOT NULL
);


ALTER TABLE "public"."Tasks" OWNER TO "postgres";


ALTER TABLE "public"."Tasks" ALTER COLUMN "task_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Tasks_task_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."UserHomeBases" (
    "user_home_base_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" bigint,
    "home_base_id" bigint
);


ALTER TABLE "public"."UserHomeBases" OWNER TO "postgres";


ALTER TABLE "public"."UserHomeBases" ALTER COLUMN "user_home_base_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."UserHomeBases_user_home_base_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."UserRoles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "role" "text" NOT NULL
);


ALTER TABLE "public"."UserRoles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."UserRolesJunction" (
    "user_roles_junction_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" bigint NOT NULL,
    "user_roles_id" bigint NOT NULL
);


ALTER TABLE "public"."UserRolesJunction" OWNER TO "postgres";


COMMENT ON TABLE "public"."UserRolesJunction" IS 'Junction Table for assigning users and roles - many-to-many';



ALTER TABLE "public"."UserRolesJunction" ALTER COLUMN "user_roles_junction_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."UserRolesJunction_user_roles_junction_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."UserRoles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."UserRoles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."UserStatuses" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "status" "text" NOT NULL
);


ALTER TABLE "public"."UserStatuses" OWNER TO "postgres";


ALTER TABLE "public"."UserStatuses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."UserStatuses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Users" (
    "user_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "email" "text" NOT NULL,
    "phone" "text",
    "clerk_user_id" "text",
    "avatar_image_url" "text",
    "role" bigint DEFAULT 1,
    "status" bigint DEFAULT 1 NOT NULL
);


ALTER TABLE "public"."Users" OWNER TO "postgres";


ALTER TABLE "public"."Users" ALTER COLUMN "user_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Users_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."WorkTrackers" (
    "work_tracker_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" bigint,
    "date" "date",
    "pickup_time" "text",
    "pickup_address_id" bigint,
    "pickup_poc" "text",
    "dropoff_time" "text",
    "dropoff_address_id" bigint,
    "dropoff_poc" "text",
    "pay_cents" bigint,
    "notes" "text",
    "bleacher_id" bigint,
    "internal_notes" "text"
);


ALTER TABLE "public"."WorkTrackers" OWNER TO "postgres";


ALTER TABLE "public"."WorkTrackers" ALTER COLUMN "work_tracker_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."WorkTrackers_work_tracker_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Addresses"
    ADD CONSTRAINT "Addresses_pkey" PRIMARY KEY ("address_id");



ALTER TABLE ONLY "public"."BleacherEvents"
    ADD CONSTRAINT "BleacherEvents_pkey" PRIMARY KEY ("bleacher_event_id");



ALTER TABLE ONLY "public"."BleacherUsers"
    ADD CONSTRAINT "BleacherUsers_pkey" PRIMARY KEY ("bleacher_user_id");



ALTER TABLE ONLY "public"."Bleachers"
    ADD CONSTRAINT "Bleachers_bleacher_number_key" UNIQUE ("bleacher_number");



ALTER TABLE ONLY "public"."Bleachers"
    ADD CONSTRAINT "Bleachers_linxup_device_id_key" UNIQUE ("linxup_device_id");



ALTER TABLE ONLY "public"."Bleachers"
    ADD CONSTRAINT "Bleachers_pkey" PRIMARY KEY ("bleacher_id");



ALTER TABLE ONLY "public"."Drivers"
    ADD CONSTRAINT "Drivers_pkey" PRIMARY KEY ("driver_id");



ALTER TABLE ONLY "public"."Events"
    ADD CONSTRAINT "Events_pkey" PRIMARY KEY ("event_id");



ALTER TABLE ONLY "public"."HomeBases"
    ADD CONSTRAINT "HomeBases_pkey" PRIMARY KEY ("home_base_id");



ALTER TABLE ONLY "public"."TaskStatuses"
    ADD CONSTRAINT "TaskStatuses_pkey" PRIMARY KEY ("task_status_id");



ALTER TABLE ONLY "public"."TaskTypes"
    ADD CONSTRAINT "TaskTypes_pkey" PRIMARY KEY ("task_type_id");



ALTER TABLE ONLY "public"."Tasks"
    ADD CONSTRAINT "Tasks_pkey" PRIMARY KEY ("task_id");



ALTER TABLE ONLY "public"."UserRolesJunction"
    ADD CONSTRAINT "UserRolesJunction_pkey" PRIMARY KEY ("user_roles_junction_id");



ALTER TABLE ONLY "public"."UserRolesJunction"
    ADD CONSTRAINT "UserRolesJunction_user_role_unique" UNIQUE ("user_id", "user_roles_id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_clerk_user_id_key" UNIQUE ("clerk_user_id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."Blocks"
    ADD CONSTRAINT "block_pkey" PRIMARY KEY ("block_id");



ALTER TABLE ONLY "public"."UserHomeBases"
    ADD CONSTRAINT "userhomebases_pkey" PRIMARY KEY ("user_home_base_id");



ALTER TABLE ONLY "public"."UserRoles"
    ADD CONSTRAINT "userroles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."UserStatuses"
    ADD CONSTRAINT "userstatuses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."WorkTrackers"
    ADD CONSTRAINT "worktrackers_pkey" PRIMARY KEY ("work_tracker_id");



ALTER TABLE ONLY "public"."BleacherEvents"
    ADD CONSTRAINT "BleacherEvents_bleacher_id_fkey" FOREIGN KEY ("bleacher_id") REFERENCES "public"."Bleachers"("bleacher_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."BleacherEvents"
    ADD CONSTRAINT "BleacherEvents_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."Events"("event_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."BleacherUsers"
    ADD CONSTRAINT "BleacherUsers_bleacher_id_fkey" FOREIGN KEY ("bleacher_id") REFERENCES "public"."Bleachers"("bleacher_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."BleacherUsers"
    ADD CONSTRAINT "BleacherUsers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("user_id");



ALTER TABLE ONLY "public"."Bleachers"
    ADD CONSTRAINT "Bleachers_home_base_id_fkey" FOREIGN KEY ("home_base_id") REFERENCES "public"."HomeBases"("home_base_id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."Bleachers"
    ADD CONSTRAINT "Bleachers_winter_home_base_id_fkey" FOREIGN KEY ("winter_home_base_id") REFERENCES "public"."HomeBases"("home_base_id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."Drivers"
    ADD CONSTRAINT "Drivers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("user_id");



ALTER TABLE ONLY "public"."Events"
    ADD CONSTRAINT "Events_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."Addresses"("address_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."Events"
    ADD CONSTRAINT "Events_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."Users"("user_id");



ALTER TABLE ONLY "public"."Tasks"
    ADD CONSTRAINT "Tasks_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."Users"("user_id");



ALTER TABLE ONLY "public"."Tasks"
    ADD CONSTRAINT "Tasks_task_status_id_fkey" FOREIGN KEY ("task_status_id") REFERENCES "public"."TaskStatuses"("task_status_id");



ALTER TABLE ONLY "public"."Tasks"
    ADD CONSTRAINT "Tasks_task_type_id_fkey" FOREIGN KEY ("task_type_id") REFERENCES "public"."TaskTypes"("task_type_id");



ALTER TABLE ONLY "public"."UserRolesJunction"
    ADD CONSTRAINT "UserRolesJunction_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."UserRolesJunction"
    ADD CONSTRAINT "UserRolesJunction_user_roles_id_fkey" FOREIGN KEY ("user_roles_id") REFERENCES "public"."UserRoles"("id");



ALTER TABLE ONLY "public"."Blocks"
    ADD CONSTRAINT "block_bleacher_id_fkey" FOREIGN KEY ("bleacher_id") REFERENCES "public"."Bleachers"("bleacher_id");



ALTER TABLE ONLY "public"."UserHomeBases"
    ADD CONSTRAINT "userhomebases_home_base_id_fkey" FOREIGN KEY ("home_base_id") REFERENCES "public"."HomeBases"("home_base_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."UserHomeBases"
    ADD CONSTRAINT "userhomebases_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("user_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."WorkTrackers"
    ADD CONSTRAINT "worktrackers_bleacher_id_fkey" FOREIGN KEY ("bleacher_id") REFERENCES "public"."Bleachers"("bleacher_id");



ALTER TABLE ONLY "public"."WorkTrackers"
    ADD CONSTRAINT "worktrackers_dropoff_address_id_fkey" FOREIGN KEY ("dropoff_address_id") REFERENCES "public"."Addresses"("address_id");



ALTER TABLE ONLY "public"."WorkTrackers"
    ADD CONSTRAINT "worktrackers_pickup_address_id_fkey" FOREIGN KEY ("pickup_address_id") REFERENCES "public"."Addresses"("address_id");



ALTER TABLE ONLY "public"."WorkTrackers"
    ADD CONSTRAINT "worktrackers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("user_id");



ALTER TABLE "public"."Addresses" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Allout All for Auth" ON "public"."UserRolesJunction" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."BleacherUsers" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."Blocks" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."Drivers" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."TaskStatuses" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."TaskTypes" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."Tasks" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."UserHomeBases" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."UserRoles" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."UserStatuses" TO "authenticated" USING (true);



CREATE POLICY "Allow All for Auth" ON "public"."WorkTrackers" TO "authenticated" USING (true);



ALTER TABLE "public"."BleacherEvents" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."BleacherUsers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Bleachers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Blocks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Drivers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."HomeBases" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."TaskStatuses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."TaskTypes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Tasks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."UserHomeBases" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."UserRoles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."UserRolesJunction" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."UserStatuses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."WorkTrackers" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "allow all for auth" ON "public"."Addresses" TO "authenticated" USING (true);



CREATE POLICY "allow all for auth" ON "public"."BleacherEvents" USING (true);



CREATE POLICY "allow all for auth" ON "public"."Bleachers" TO "authenticated" USING (true);



CREATE POLICY "allow all for auth" ON "public"."Events" TO "authenticated" USING (true);



CREATE POLICY "allow all for auth" ON "public"."HomeBases" TO "authenticated" USING (true);



CREATE POLICY "allow all for auth" ON "public"."Users" TO "authenticated" USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Addresses";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."BleacherEvents";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Bleachers";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Events";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."HomeBases";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Users";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."Addresses" TO "anon";
GRANT ALL ON TABLE "public"."Addresses" TO "authenticated";
GRANT ALL ON TABLE "public"."Addresses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Addresses_address_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Addresses_address_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Addresses_address_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."BleacherEvents" TO "anon";
GRANT ALL ON TABLE "public"."BleacherEvents" TO "authenticated";
GRANT ALL ON TABLE "public"."BleacherEvents" TO "service_role";



GRANT ALL ON SEQUENCE "public"."BleacherEvents_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."BleacherEvents_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."BleacherEvents_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."BleacherUsers" TO "anon";
GRANT ALL ON TABLE "public"."BleacherUsers" TO "authenticated";
GRANT ALL ON TABLE "public"."BleacherUsers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."BleacherUsers_bleacher_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."BleacherUsers_bleacher_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."BleacherUsers_bleacher_user_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Bleachers" TO "anon";
GRANT ALL ON TABLE "public"."Bleachers" TO "authenticated";
GRANT ALL ON TABLE "public"."Bleachers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Bleachers_bleacher_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Bleachers_bleacher_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Bleachers_bleacher_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Blocks" TO "anon";
GRANT ALL ON TABLE "public"."Blocks" TO "authenticated";
GRANT ALL ON TABLE "public"."Blocks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Blocks_block_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Blocks_block_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Blocks_block_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Drivers" TO "anon";
GRANT ALL ON TABLE "public"."Drivers" TO "authenticated";
GRANT ALL ON TABLE "public"."Drivers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Drivers_driver_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Drivers_driver_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Drivers_driver_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Events" TO "anon";
GRANT ALL ON TABLE "public"."Events" TO "authenticated";
GRANT ALL ON TABLE "public"."Events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."HomeBases" TO "anon";
GRANT ALL ON TABLE "public"."HomeBases" TO "authenticated";
GRANT ALL ON TABLE "public"."HomeBases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."HomeBases_home_base_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."HomeBases_home_base_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."HomeBases_home_base_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."TaskStatuses" TO "anon";
GRANT ALL ON TABLE "public"."TaskStatuses" TO "authenticated";
GRANT ALL ON TABLE "public"."TaskStatuses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TaskStatuses_task_status_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TaskStatuses_task_status_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TaskStatuses_task_status_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."TaskTypes" TO "anon";
GRANT ALL ON TABLE "public"."TaskTypes" TO "authenticated";
GRANT ALL ON TABLE "public"."TaskTypes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TaskTypes_task_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TaskTypes_task_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TaskTypes_task_type_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Tasks" TO "anon";
GRANT ALL ON TABLE "public"."Tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."Tasks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Tasks_task_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Tasks_task_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Tasks_task_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."UserHomeBases" TO "anon";
GRANT ALL ON TABLE "public"."UserHomeBases" TO "authenticated";
GRANT ALL ON TABLE "public"."UserHomeBases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."UserHomeBases_user_home_base_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."UserHomeBases_user_home_base_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."UserHomeBases_user_home_base_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."UserRoles" TO "anon";
GRANT ALL ON TABLE "public"."UserRoles" TO "authenticated";
GRANT ALL ON TABLE "public"."UserRoles" TO "service_role";



GRANT ALL ON TABLE "public"."UserRolesJunction" TO "anon";
GRANT ALL ON TABLE "public"."UserRolesJunction" TO "authenticated";
GRANT ALL ON TABLE "public"."UserRolesJunction" TO "service_role";



GRANT ALL ON SEQUENCE "public"."UserRolesJunction_user_roles_junction_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."UserRolesJunction_user_roles_junction_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."UserRolesJunction_user_roles_junction_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."UserRoles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."UserRoles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."UserRoles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."UserStatuses" TO "anon";
GRANT ALL ON TABLE "public"."UserStatuses" TO "authenticated";
GRANT ALL ON TABLE "public"."UserStatuses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."UserStatuses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."UserStatuses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."UserStatuses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Users" TO "anon";
GRANT ALL ON TABLE "public"."Users" TO "authenticated";
GRANT ALL ON TABLE "public"."Users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Users_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Users_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Users_user_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."WorkTrackers" TO "anon";
GRANT ALL ON TABLE "public"."WorkTrackers" TO "authenticated";
GRANT ALL ON TABLE "public"."WorkTrackers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."WorkTrackers_work_tracker_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."WorkTrackers_work_tracker_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."WorkTrackers_work_tracker_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























