export type SelectBleacher = {
  id: string;
  created_at: string;
  bleacher_number: number;
  summer_home_base_uuid: string;
  winter_home_base_uuid: string;
  bleacher_rows: number;
  bleacher_seats: number;
  linxup_device_id: string | null;
  summer_account_manager_uuid: string | null;
  winter_account_manager_uuid: string | null;
  hitch_type: string | null;
  vin_number: string | null;
  tag_number: string | null;
  manufacturer: string | null;
  height_folded_ft: number | null;
  gvwr: number | null;
  bleacher_length: number | null;
  opening_direction: "driver" | "passenger" | null;
  nvis_pdf_path: string | null;
};

export type InsertBleacher = {
  bleacher_number: number;
  summer_home_base_uuid: string;
  winter_home_base_uuid: string;
  bleacher_rows: number;
  bleacher_seats: number;
  linxup_device_id?: string | null;
  summer_account_manager_uuid?: string | null;
  winter_account_manager_uuid?: string | null;
  hitch_type?: string | null;
  vin_number?: string | null;
  tag_number?: string | null;
  manufacturer?: string | null;
  height_folded_ft?: number | null;
  gvwr?: number | null;
  trailer_length?: number | null;
  opening_direction?: "driver" | "passenger" | null;
  nvis_pdf_path: string | null;
};

export type UpdateBleacher = {
  id: string;
  bleacher_number: number;
  summer_home_base_uuid: string;
  winter_home_base_uuid: string;
  bleacher_rows: number;
  bleacher_seats: number;
  linxup_device_id?: string | null;
  summer_account_manager_uuid?: string | null;
  winter_account_manager_uuid?: string | null;
  hitch_type?: string | null;
  vin_number?: string | null;
  tag_number?: string | null;
  manufacturer?: string | null;
  height_folded_ft?: number | null;
  gvwr?: number | null;
  trailer_length?: number | null;
  opening_direction?: "driver" | "passenger" | null;
  nvis_pdf_path: string | null;
};
