
  create table "public"."Addresses" (
    "address_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "street" text not null,
    "city" text not null,
    "state_province" text not null,
    "zip_postal" text
      );


alter table "public"."Addresses" enable row level security;


  create table "public"."BleacherEvents" (
    "bleacher_event_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "bleacher_id" bigint not null,
    "event_id" bigint not null,
    "setup_text" text,
    "setup_confirmed" boolean not null default false,
    "teardown_text" text,
    "teardown_confirmed" boolean not null default false
      );


alter table "public"."BleacherEvents" enable row level security;


  create table "public"."BleacherUsers" (
    "bleacher_user_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "bleacher_id" bigint not null,
    "season" text not null
      );


alter table "public"."BleacherUsers" enable row level security;


  create table "public"."Bleachers" (
    "bleacher_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "bleacher_number" smallint not null,
    "home_base_id" bigint not null,
    "winter_home_base_id" bigint not null,
    "bleacher_rows" smallint not null,
    "bleacher_seats" smallint not null,
    "created_by" uuid,
    "updated_at" timestamp without time zone,
    "updated_by" uuid,
    "linxup_device_id" text
      );


alter table "public"."Bleachers" enable row level security;


  create table "public"."Blocks" (
    "block_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "bleacher_id" bigint,
    "text" text,
    "date" date
      );


alter table "public"."Blocks" enable row level security;


  create table "public"."Drivers" (
    "driver_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "tax" smallint not null default '0'::smallint,
    "pay_rate_cents" smallint not null default '0'::smallint,
    "pay_currency" text not null default 'CAD'::text,
    "pay_per_unit" text not null default 'KM'::text
      );


alter table "public"."Drivers" enable row level security;


  create table "public"."Events" (
    "event_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_name" text not null,
    "setup_start" date,
    "event_start" date not null,
    "event_end" date not null,
    "teardown_end" date,
    "address_id" bigint not null,
    "total_seats" integer,
    "seven_row" smallint,
    "ten_row" smallint,
    "fifteen_row" smallint,
    "lenient" boolean not null,
    "booked" boolean not null default false,
    "notes" text,
    "must_be_clean" boolean not null default false,
    "hsl_hue" smallint,
    "goodshuffle_url" text,
    "created_by_user_id" bigint
      );


alter table "public"."Events" enable row level security;


  create table "public"."HomeBases" (
    "home_base_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "home_base_name" text not null
      );


alter table "public"."HomeBases" enable row level security;


  create table "public"."TaskStatuses" (
    "task_status_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "label" text not null,
    "hex" text not null
      );


alter table "public"."TaskStatuses" enable row level security;


  create table "public"."TaskTypes" (
    "task_type_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "label" text not null
      );


alter table "public"."TaskTypes" enable row level security;


  create table "public"."Tasks" (
    "task_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text not null,
    "created_by_user_id" bigint not null,
    "task_type_id" bigint not null,
    "task_status_id" bigint not null
      );


alter table "public"."Tasks" enable row level security;


  create table "public"."UserHomeBases" (
    "user_home_base_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "home_base_id" bigint
      );


alter table "public"."UserHomeBases" enable row level security;


  create table "public"."UserRoles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role" text not null
      );


alter table "public"."UserRoles" enable row level security;


  create table "public"."UserRolesJunction" (
    "user_roles_junction_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "user_roles_id" bigint not null
      );


alter table "public"."UserRolesJunction" enable row level security;


  create table "public"."UserStatuses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "status" text not null
      );


alter table "public"."UserStatuses" enable row level security;


  create table "public"."Users" (
    "user_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text,
    "last_name" text,
    "email" text not null,
    "phone" text,
    "clerk_user_id" text,
    "avatar_image_url" text,
    "role" bigint default 1,
    "status" bigint not null default 1
      );


alter table "public"."Users" enable row level security;


  create table "public"."WorkTrackers" (
    "work_tracker_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "date" date,
    "pickup_time" text,
    "pickup_address_id" bigint,
    "pickup_poc" text,
    "dropoff_time" text,
    "dropoff_address_id" bigint,
    "dropoff_poc" text,
    "pay_cents" bigint,
    "notes" text,
    "bleacher_id" bigint,
    "internal_notes" text
      );


alter table "public"."WorkTrackers" enable row level security;

CREATE UNIQUE INDEX "Addresses_pkey" ON public."Addresses" USING btree (address_id);

CREATE UNIQUE INDEX "BleacherEvents_pkey" ON public."BleacherEvents" USING btree (bleacher_event_id);

CREATE UNIQUE INDEX "BleacherUsers_pkey" ON public."BleacherUsers" USING btree (bleacher_user_id);

CREATE UNIQUE INDEX "Bleachers_bleacher_number_key" ON public."Bleachers" USING btree (bleacher_number);

CREATE UNIQUE INDEX "Bleachers_linxup_device_id_key" ON public."Bleachers" USING btree (linxup_device_id);

CREATE UNIQUE INDEX "Bleachers_pkey" ON public."Bleachers" USING btree (bleacher_id);

CREATE UNIQUE INDEX "Drivers_pkey" ON public."Drivers" USING btree (driver_id);

CREATE UNIQUE INDEX "Events_pkey" ON public."Events" USING btree (event_id);

CREATE UNIQUE INDEX "HomeBases_pkey" ON public."HomeBases" USING btree (home_base_id);

CREATE UNIQUE INDEX "TaskStatuses_pkey" ON public."TaskStatuses" USING btree (task_status_id);

CREATE UNIQUE INDEX "TaskTypes_pkey" ON public."TaskTypes" USING btree (task_type_id);

CREATE UNIQUE INDEX "Tasks_pkey" ON public."Tasks" USING btree (task_id);

CREATE UNIQUE INDEX "UserRolesJunction_pkey" ON public."UserRolesJunction" USING btree (user_roles_junction_id);

CREATE UNIQUE INDEX "UserRolesJunction_user_role_unique" ON public."UserRolesJunction" USING btree (user_id, user_roles_id);

CREATE UNIQUE INDEX "Users_clerk_user_id_key" ON public."Users" USING btree (clerk_user_id);

CREATE UNIQUE INDEX "Users_email_key" ON public."Users" USING btree (email);

CREATE UNIQUE INDEX "Users_pkey" ON public."Users" USING btree (user_id);

CREATE UNIQUE INDEX block_pkey ON public."Blocks" USING btree (block_id);

CREATE UNIQUE INDEX userhomebases_pkey ON public."UserHomeBases" USING btree (user_home_base_id);

CREATE UNIQUE INDEX userroles_pkey ON public."UserRoles" USING btree (id);

CREATE UNIQUE INDEX userstatuses_pkey ON public."UserStatuses" USING btree (id);

CREATE UNIQUE INDEX worktrackers_pkey ON public."WorkTrackers" USING btree (work_tracker_id);

alter table "public"."Addresses" add constraint "Addresses_pkey" PRIMARY KEY using index "Addresses_pkey";

alter table "public"."BleacherEvents" add constraint "BleacherEvents_pkey" PRIMARY KEY using index "BleacherEvents_pkey";

alter table "public"."BleacherUsers" add constraint "BleacherUsers_pkey" PRIMARY KEY using index "BleacherUsers_pkey";

alter table "public"."Bleachers" add constraint "Bleachers_pkey" PRIMARY KEY using index "Bleachers_pkey";

alter table "public"."Blocks" add constraint "block_pkey" PRIMARY KEY using index "block_pkey";

alter table "public"."Drivers" add constraint "Drivers_pkey" PRIMARY KEY using index "Drivers_pkey";

alter table "public"."Events" add constraint "Events_pkey" PRIMARY KEY using index "Events_pkey";

alter table "public"."HomeBases" add constraint "HomeBases_pkey" PRIMARY KEY using index "HomeBases_pkey";

alter table "public"."TaskStatuses" add constraint "TaskStatuses_pkey" PRIMARY KEY using index "TaskStatuses_pkey";

alter table "public"."TaskTypes" add constraint "TaskTypes_pkey" PRIMARY KEY using index "TaskTypes_pkey";

alter table "public"."Tasks" add constraint "Tasks_pkey" PRIMARY KEY using index "Tasks_pkey";

alter table "public"."UserHomeBases" add constraint "userhomebases_pkey" PRIMARY KEY using index "userhomebases_pkey";

alter table "public"."UserRoles" add constraint "userroles_pkey" PRIMARY KEY using index "userroles_pkey";

alter table "public"."UserRolesJunction" add constraint "UserRolesJunction_pkey" PRIMARY KEY using index "UserRolesJunction_pkey";

alter table "public"."UserStatuses" add constraint "userstatuses_pkey" PRIMARY KEY using index "userstatuses_pkey";

alter table "public"."Users" add constraint "Users_pkey" PRIMARY KEY using index "Users_pkey";

alter table "public"."WorkTrackers" add constraint "worktrackers_pkey" PRIMARY KEY using index "worktrackers_pkey";

alter table "public"."BleacherEvents" add constraint "BleacherEvents_bleacher_id_fkey" FOREIGN KEY (bleacher_id) REFERENCES public."Bleachers"(bleacher_id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."BleacherEvents" validate constraint "BleacherEvents_bleacher_id_fkey";

alter table "public"."BleacherEvents" add constraint "BleacherEvents_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public."Events"(event_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."BleacherEvents" validate constraint "BleacherEvents_event_id_fkey";

alter table "public"."BleacherUsers" add constraint "BleacherUsers_bleacher_id_fkey" FOREIGN KEY (bleacher_id) REFERENCES public."Bleachers"(bleacher_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."BleacherUsers" validate constraint "BleacherUsers_bleacher_id_fkey";

alter table "public"."BleacherUsers" add constraint "BleacherUsers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(user_id) not valid;

alter table "public"."BleacherUsers" validate constraint "BleacherUsers_user_id_fkey";

alter table "public"."Bleachers" add constraint "Bleachers_bleacher_number_key" UNIQUE using index "Bleachers_bleacher_number_key";

alter table "public"."Bleachers" add constraint "Bleachers_home_base_id_fkey" FOREIGN KEY (home_base_id) REFERENCES public."HomeBases"(home_base_id) ON UPDATE CASCADE not valid;

alter table "public"."Bleachers" validate constraint "Bleachers_home_base_id_fkey";

alter table "public"."Bleachers" add constraint "Bleachers_linxup_device_id_key" UNIQUE using index "Bleachers_linxup_device_id_key";

alter table "public"."Bleachers" add constraint "Bleachers_winter_home_base_id_fkey" FOREIGN KEY (winter_home_base_id) REFERENCES public."HomeBases"(home_base_id) ON UPDATE CASCADE not valid;

alter table "public"."Bleachers" validate constraint "Bleachers_winter_home_base_id_fkey";

alter table "public"."Blocks" add constraint "block_bleacher_id_fkey" FOREIGN KEY (bleacher_id) REFERENCES public."Bleachers"(bleacher_id) not valid;

alter table "public"."Blocks" validate constraint "block_bleacher_id_fkey";

alter table "public"."Drivers" add constraint "Drivers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(user_id) not valid;

alter table "public"."Drivers" validate constraint "Drivers_user_id_fkey";

alter table "public"."Events" add constraint "Events_address_id_fkey" FOREIGN KEY (address_id) REFERENCES public."Addresses"(address_id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."Events" validate constraint "Events_address_id_fkey";

alter table "public"."Events" add constraint "Events_created_by_user_id_fkey" FOREIGN KEY (created_by_user_id) REFERENCES public."Users"(user_id) not valid;

alter table "public"."Events" validate constraint "Events_created_by_user_id_fkey";

alter table "public"."Tasks" add constraint "Tasks_created_by_user_id_fkey" FOREIGN KEY (created_by_user_id) REFERENCES public."Users"(user_id) not valid;

alter table "public"."Tasks" validate constraint "Tasks_created_by_user_id_fkey";

alter table "public"."Tasks" add constraint "Tasks_task_status_id_fkey" FOREIGN KEY (task_status_id) REFERENCES public."TaskStatuses"(task_status_id) not valid;

alter table "public"."Tasks" validate constraint "Tasks_task_status_id_fkey";

alter table "public"."Tasks" add constraint "Tasks_task_type_id_fkey" FOREIGN KEY (task_type_id) REFERENCES public."TaskTypes"(task_type_id) not valid;

alter table "public"."Tasks" validate constraint "Tasks_task_type_id_fkey";

alter table "public"."UserHomeBases" add constraint "userhomebases_home_base_id_fkey" FOREIGN KEY (home_base_id) REFERENCES public."HomeBases"(home_base_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."UserHomeBases" validate constraint "userhomebases_home_base_id_fkey";

alter table "public"."UserHomeBases" add constraint "userhomebases_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."UserHomeBases" validate constraint "userhomebases_user_id_fkey";

alter table "public"."UserRolesJunction" add constraint "UserRolesJunction_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."UserRolesJunction" validate constraint "UserRolesJunction_user_id_fkey";

alter table "public"."UserRolesJunction" add constraint "UserRolesJunction_user_role_unique" UNIQUE using index "UserRolesJunction_user_role_unique";

alter table "public"."UserRolesJunction" add constraint "UserRolesJunction_user_roles_id_fkey" FOREIGN KEY (user_roles_id) REFERENCES public."UserRoles"(id) not valid;

alter table "public"."UserRolesJunction" validate constraint "UserRolesJunction_user_roles_id_fkey";

alter table "public"."Users" add constraint "Users_clerk_user_id_key" UNIQUE using index "Users_clerk_user_id_key";

alter table "public"."Users" add constraint "Users_email_key" UNIQUE using index "Users_email_key";

alter table "public"."WorkTrackers" add constraint "worktrackers_bleacher_id_fkey" FOREIGN KEY (bleacher_id) REFERENCES public."Bleachers"(bleacher_id) not valid;

alter table "public"."WorkTrackers" validate constraint "worktrackers_bleacher_id_fkey";

alter table "public"."WorkTrackers" add constraint "worktrackers_dropoff_address_id_fkey" FOREIGN KEY (dropoff_address_id) REFERENCES public."Addresses"(address_id) not valid;

alter table "public"."WorkTrackers" validate constraint "worktrackers_dropoff_address_id_fkey";

alter table "public"."WorkTrackers" add constraint "worktrackers_pickup_address_id_fkey" FOREIGN KEY (pickup_address_id) REFERENCES public."Addresses"(address_id) not valid;

alter table "public"."WorkTrackers" validate constraint "worktrackers_pickup_address_id_fkey";

alter table "public"."WorkTrackers" add constraint "worktrackers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."Users"(user_id) not valid;

alter table "public"."WorkTrackers" validate constraint "worktrackers_user_id_fkey";

grant delete on table "public"."Addresses" to "anon";

grant insert on table "public"."Addresses" to "anon";

grant references on table "public"."Addresses" to "anon";

grant select on table "public"."Addresses" to "anon";

grant trigger on table "public"."Addresses" to "anon";

grant truncate on table "public"."Addresses" to "anon";

grant update on table "public"."Addresses" to "anon";

grant delete on table "public"."Addresses" to "authenticated";

grant insert on table "public"."Addresses" to "authenticated";

grant references on table "public"."Addresses" to "authenticated";

grant select on table "public"."Addresses" to "authenticated";

grant trigger on table "public"."Addresses" to "authenticated";

grant truncate on table "public"."Addresses" to "authenticated";

grant update on table "public"."Addresses" to "authenticated";

grant delete on table "public"."Addresses" to "service_role";

grant insert on table "public"."Addresses" to "service_role";

grant references on table "public"."Addresses" to "service_role";

grant select on table "public"."Addresses" to "service_role";

grant trigger on table "public"."Addresses" to "service_role";

grant truncate on table "public"."Addresses" to "service_role";

grant update on table "public"."Addresses" to "service_role";

grant delete on table "public"."BleacherEvents" to "anon";

grant insert on table "public"."BleacherEvents" to "anon";

grant references on table "public"."BleacherEvents" to "anon";

grant select on table "public"."BleacherEvents" to "anon";

grant trigger on table "public"."BleacherEvents" to "anon";

grant truncate on table "public"."BleacherEvents" to "anon";

grant update on table "public"."BleacherEvents" to "anon";

grant delete on table "public"."BleacherEvents" to "authenticated";

grant insert on table "public"."BleacherEvents" to "authenticated";

grant references on table "public"."BleacherEvents" to "authenticated";

grant select on table "public"."BleacherEvents" to "authenticated";

grant trigger on table "public"."BleacherEvents" to "authenticated";

grant truncate on table "public"."BleacherEvents" to "authenticated";

grant update on table "public"."BleacherEvents" to "authenticated";

grant delete on table "public"."BleacherEvents" to "service_role";

grant insert on table "public"."BleacherEvents" to "service_role";

grant references on table "public"."BleacherEvents" to "service_role";

grant select on table "public"."BleacherEvents" to "service_role";

grant trigger on table "public"."BleacherEvents" to "service_role";

grant truncate on table "public"."BleacherEvents" to "service_role";

grant update on table "public"."BleacherEvents" to "service_role";

grant delete on table "public"."BleacherUsers" to "anon";

grant insert on table "public"."BleacherUsers" to "anon";

grant references on table "public"."BleacherUsers" to "anon";

grant select on table "public"."BleacherUsers" to "anon";

grant trigger on table "public"."BleacherUsers" to "anon";

grant truncate on table "public"."BleacherUsers" to "anon";

grant update on table "public"."BleacherUsers" to "anon";

grant delete on table "public"."BleacherUsers" to "authenticated";

grant insert on table "public"."BleacherUsers" to "authenticated";

grant references on table "public"."BleacherUsers" to "authenticated";

grant select on table "public"."BleacherUsers" to "authenticated";

grant trigger on table "public"."BleacherUsers" to "authenticated";

grant truncate on table "public"."BleacherUsers" to "authenticated";

grant update on table "public"."BleacherUsers" to "authenticated";

grant delete on table "public"."BleacherUsers" to "service_role";

grant insert on table "public"."BleacherUsers" to "service_role";

grant references on table "public"."BleacherUsers" to "service_role";

grant select on table "public"."BleacherUsers" to "service_role";

grant trigger on table "public"."BleacherUsers" to "service_role";

grant truncate on table "public"."BleacherUsers" to "service_role";

grant update on table "public"."BleacherUsers" to "service_role";

grant delete on table "public"."Bleachers" to "anon";

grant insert on table "public"."Bleachers" to "anon";

grant references on table "public"."Bleachers" to "anon";

grant select on table "public"."Bleachers" to "anon";

grant trigger on table "public"."Bleachers" to "anon";

grant truncate on table "public"."Bleachers" to "anon";

grant update on table "public"."Bleachers" to "anon";

grant delete on table "public"."Bleachers" to "authenticated";

grant insert on table "public"."Bleachers" to "authenticated";

grant references on table "public"."Bleachers" to "authenticated";

grant select on table "public"."Bleachers" to "authenticated";

grant trigger on table "public"."Bleachers" to "authenticated";

grant truncate on table "public"."Bleachers" to "authenticated";

grant update on table "public"."Bleachers" to "authenticated";

grant delete on table "public"."Bleachers" to "service_role";

grant insert on table "public"."Bleachers" to "service_role";

grant references on table "public"."Bleachers" to "service_role";

grant select on table "public"."Bleachers" to "service_role";

grant trigger on table "public"."Bleachers" to "service_role";

grant truncate on table "public"."Bleachers" to "service_role";

grant update on table "public"."Bleachers" to "service_role";

grant delete on table "public"."Blocks" to "anon";

grant insert on table "public"."Blocks" to "anon";

grant references on table "public"."Blocks" to "anon";

grant select on table "public"."Blocks" to "anon";

grant trigger on table "public"."Blocks" to "anon";

grant truncate on table "public"."Blocks" to "anon";

grant update on table "public"."Blocks" to "anon";

grant delete on table "public"."Blocks" to "authenticated";

grant insert on table "public"."Blocks" to "authenticated";

grant references on table "public"."Blocks" to "authenticated";

grant select on table "public"."Blocks" to "authenticated";

grant trigger on table "public"."Blocks" to "authenticated";

grant truncate on table "public"."Blocks" to "authenticated";

grant update on table "public"."Blocks" to "authenticated";

grant delete on table "public"."Blocks" to "service_role";

grant insert on table "public"."Blocks" to "service_role";

grant references on table "public"."Blocks" to "service_role";

grant select on table "public"."Blocks" to "service_role";

grant trigger on table "public"."Blocks" to "service_role";

grant truncate on table "public"."Blocks" to "service_role";

grant update on table "public"."Blocks" to "service_role";

grant delete on table "public"."Drivers" to "anon";

grant insert on table "public"."Drivers" to "anon";

grant references on table "public"."Drivers" to "anon";

grant select on table "public"."Drivers" to "anon";

grant trigger on table "public"."Drivers" to "anon";

grant truncate on table "public"."Drivers" to "anon";

grant update on table "public"."Drivers" to "anon";

grant delete on table "public"."Drivers" to "authenticated";

grant insert on table "public"."Drivers" to "authenticated";

grant references on table "public"."Drivers" to "authenticated";

grant select on table "public"."Drivers" to "authenticated";

grant trigger on table "public"."Drivers" to "authenticated";

grant truncate on table "public"."Drivers" to "authenticated";

grant update on table "public"."Drivers" to "authenticated";

grant delete on table "public"."Drivers" to "service_role";

grant insert on table "public"."Drivers" to "service_role";

grant references on table "public"."Drivers" to "service_role";

grant select on table "public"."Drivers" to "service_role";

grant trigger on table "public"."Drivers" to "service_role";

grant truncate on table "public"."Drivers" to "service_role";

grant update on table "public"."Drivers" to "service_role";

grant delete on table "public"."Events" to "anon";

grant insert on table "public"."Events" to "anon";

grant references on table "public"."Events" to "anon";

grant select on table "public"."Events" to "anon";

grant trigger on table "public"."Events" to "anon";

grant truncate on table "public"."Events" to "anon";

grant update on table "public"."Events" to "anon";

grant delete on table "public"."Events" to "authenticated";

grant insert on table "public"."Events" to "authenticated";

grant references on table "public"."Events" to "authenticated";

grant select on table "public"."Events" to "authenticated";

grant trigger on table "public"."Events" to "authenticated";

grant truncate on table "public"."Events" to "authenticated";

grant update on table "public"."Events" to "authenticated";

grant delete on table "public"."Events" to "service_role";

grant insert on table "public"."Events" to "service_role";

grant references on table "public"."Events" to "service_role";

grant select on table "public"."Events" to "service_role";

grant trigger on table "public"."Events" to "service_role";

grant truncate on table "public"."Events" to "service_role";

grant update on table "public"."Events" to "service_role";

grant delete on table "public"."HomeBases" to "anon";

grant insert on table "public"."HomeBases" to "anon";

grant references on table "public"."HomeBases" to "anon";

grant select on table "public"."HomeBases" to "anon";

grant trigger on table "public"."HomeBases" to "anon";

grant truncate on table "public"."HomeBases" to "anon";

grant update on table "public"."HomeBases" to "anon";

grant delete on table "public"."HomeBases" to "authenticated";

grant insert on table "public"."HomeBases" to "authenticated";

grant references on table "public"."HomeBases" to "authenticated";

grant select on table "public"."HomeBases" to "authenticated";

grant trigger on table "public"."HomeBases" to "authenticated";

grant truncate on table "public"."HomeBases" to "authenticated";

grant update on table "public"."HomeBases" to "authenticated";

grant delete on table "public"."HomeBases" to "service_role";

grant insert on table "public"."HomeBases" to "service_role";

grant references on table "public"."HomeBases" to "service_role";

grant select on table "public"."HomeBases" to "service_role";

grant trigger on table "public"."HomeBases" to "service_role";

grant truncate on table "public"."HomeBases" to "service_role";

grant update on table "public"."HomeBases" to "service_role";

grant delete on table "public"."TaskStatuses" to "anon";

grant insert on table "public"."TaskStatuses" to "anon";

grant references on table "public"."TaskStatuses" to "anon";

grant select on table "public"."TaskStatuses" to "anon";

grant trigger on table "public"."TaskStatuses" to "anon";

grant truncate on table "public"."TaskStatuses" to "anon";

grant update on table "public"."TaskStatuses" to "anon";

grant delete on table "public"."TaskStatuses" to "authenticated";

grant insert on table "public"."TaskStatuses" to "authenticated";

grant references on table "public"."TaskStatuses" to "authenticated";

grant select on table "public"."TaskStatuses" to "authenticated";

grant trigger on table "public"."TaskStatuses" to "authenticated";

grant truncate on table "public"."TaskStatuses" to "authenticated";

grant update on table "public"."TaskStatuses" to "authenticated";

grant delete on table "public"."TaskStatuses" to "service_role";

grant insert on table "public"."TaskStatuses" to "service_role";

grant references on table "public"."TaskStatuses" to "service_role";

grant select on table "public"."TaskStatuses" to "service_role";

grant trigger on table "public"."TaskStatuses" to "service_role";

grant truncate on table "public"."TaskStatuses" to "service_role";

grant update on table "public"."TaskStatuses" to "service_role";

grant delete on table "public"."TaskTypes" to "anon";

grant insert on table "public"."TaskTypes" to "anon";

grant references on table "public"."TaskTypes" to "anon";

grant select on table "public"."TaskTypes" to "anon";

grant trigger on table "public"."TaskTypes" to "anon";

grant truncate on table "public"."TaskTypes" to "anon";

grant update on table "public"."TaskTypes" to "anon";

grant delete on table "public"."TaskTypes" to "authenticated";

grant insert on table "public"."TaskTypes" to "authenticated";

grant references on table "public"."TaskTypes" to "authenticated";

grant select on table "public"."TaskTypes" to "authenticated";

grant trigger on table "public"."TaskTypes" to "authenticated";

grant truncate on table "public"."TaskTypes" to "authenticated";

grant update on table "public"."TaskTypes" to "authenticated";

grant delete on table "public"."TaskTypes" to "service_role";

grant insert on table "public"."TaskTypes" to "service_role";

grant references on table "public"."TaskTypes" to "service_role";

grant select on table "public"."TaskTypes" to "service_role";

grant trigger on table "public"."TaskTypes" to "service_role";

grant truncate on table "public"."TaskTypes" to "service_role";

grant update on table "public"."TaskTypes" to "service_role";

grant delete on table "public"."Tasks" to "anon";

grant insert on table "public"."Tasks" to "anon";

grant references on table "public"."Tasks" to "anon";

grant select on table "public"."Tasks" to "anon";

grant trigger on table "public"."Tasks" to "anon";

grant truncate on table "public"."Tasks" to "anon";

grant update on table "public"."Tasks" to "anon";

grant delete on table "public"."Tasks" to "authenticated";

grant insert on table "public"."Tasks" to "authenticated";

grant references on table "public"."Tasks" to "authenticated";

grant select on table "public"."Tasks" to "authenticated";

grant trigger on table "public"."Tasks" to "authenticated";

grant truncate on table "public"."Tasks" to "authenticated";

grant update on table "public"."Tasks" to "authenticated";

grant delete on table "public"."Tasks" to "service_role";

grant insert on table "public"."Tasks" to "service_role";

grant references on table "public"."Tasks" to "service_role";

grant select on table "public"."Tasks" to "service_role";

grant trigger on table "public"."Tasks" to "service_role";

grant truncate on table "public"."Tasks" to "service_role";

grant update on table "public"."Tasks" to "service_role";

grant delete on table "public"."UserHomeBases" to "anon";

grant insert on table "public"."UserHomeBases" to "anon";

grant references on table "public"."UserHomeBases" to "anon";

grant select on table "public"."UserHomeBases" to "anon";

grant trigger on table "public"."UserHomeBases" to "anon";

grant truncate on table "public"."UserHomeBases" to "anon";

grant update on table "public"."UserHomeBases" to "anon";

grant delete on table "public"."UserHomeBases" to "authenticated";

grant insert on table "public"."UserHomeBases" to "authenticated";

grant references on table "public"."UserHomeBases" to "authenticated";

grant select on table "public"."UserHomeBases" to "authenticated";

grant trigger on table "public"."UserHomeBases" to "authenticated";

grant truncate on table "public"."UserHomeBases" to "authenticated";

grant update on table "public"."UserHomeBases" to "authenticated";

grant delete on table "public"."UserHomeBases" to "service_role";

grant insert on table "public"."UserHomeBases" to "service_role";

grant references on table "public"."UserHomeBases" to "service_role";

grant select on table "public"."UserHomeBases" to "service_role";

grant trigger on table "public"."UserHomeBases" to "service_role";

grant truncate on table "public"."UserHomeBases" to "service_role";

grant update on table "public"."UserHomeBases" to "service_role";

grant delete on table "public"."UserRoles" to "anon";

grant insert on table "public"."UserRoles" to "anon";

grant references on table "public"."UserRoles" to "anon";

grant select on table "public"."UserRoles" to "anon";

grant trigger on table "public"."UserRoles" to "anon";

grant truncate on table "public"."UserRoles" to "anon";

grant update on table "public"."UserRoles" to "anon";

grant delete on table "public"."UserRoles" to "authenticated";

grant insert on table "public"."UserRoles" to "authenticated";

grant references on table "public"."UserRoles" to "authenticated";

grant select on table "public"."UserRoles" to "authenticated";

grant trigger on table "public"."UserRoles" to "authenticated";

grant truncate on table "public"."UserRoles" to "authenticated";

grant update on table "public"."UserRoles" to "authenticated";

grant delete on table "public"."UserRoles" to "service_role";

grant insert on table "public"."UserRoles" to "service_role";

grant references on table "public"."UserRoles" to "service_role";

grant select on table "public"."UserRoles" to "service_role";

grant trigger on table "public"."UserRoles" to "service_role";

grant truncate on table "public"."UserRoles" to "service_role";

grant update on table "public"."UserRoles" to "service_role";

grant delete on table "public"."UserRolesJunction" to "anon";

grant insert on table "public"."UserRolesJunction" to "anon";

grant references on table "public"."UserRolesJunction" to "anon";

grant select on table "public"."UserRolesJunction" to "anon";

grant trigger on table "public"."UserRolesJunction" to "anon";

grant truncate on table "public"."UserRolesJunction" to "anon";

grant update on table "public"."UserRolesJunction" to "anon";

grant delete on table "public"."UserRolesJunction" to "authenticated";

grant insert on table "public"."UserRolesJunction" to "authenticated";

grant references on table "public"."UserRolesJunction" to "authenticated";

grant select on table "public"."UserRolesJunction" to "authenticated";

grant trigger on table "public"."UserRolesJunction" to "authenticated";

grant truncate on table "public"."UserRolesJunction" to "authenticated";

grant update on table "public"."UserRolesJunction" to "authenticated";

grant delete on table "public"."UserRolesJunction" to "service_role";

grant insert on table "public"."UserRolesJunction" to "service_role";

grant references on table "public"."UserRolesJunction" to "service_role";

grant select on table "public"."UserRolesJunction" to "service_role";

grant trigger on table "public"."UserRolesJunction" to "service_role";

grant truncate on table "public"."UserRolesJunction" to "service_role";

grant update on table "public"."UserRolesJunction" to "service_role";

grant delete on table "public"."UserStatuses" to "anon";

grant insert on table "public"."UserStatuses" to "anon";

grant references on table "public"."UserStatuses" to "anon";

grant select on table "public"."UserStatuses" to "anon";

grant trigger on table "public"."UserStatuses" to "anon";

grant truncate on table "public"."UserStatuses" to "anon";

grant update on table "public"."UserStatuses" to "anon";

grant delete on table "public"."UserStatuses" to "authenticated";

grant insert on table "public"."UserStatuses" to "authenticated";

grant references on table "public"."UserStatuses" to "authenticated";

grant select on table "public"."UserStatuses" to "authenticated";

grant trigger on table "public"."UserStatuses" to "authenticated";

grant truncate on table "public"."UserStatuses" to "authenticated";

grant update on table "public"."UserStatuses" to "authenticated";

grant delete on table "public"."UserStatuses" to "service_role";

grant insert on table "public"."UserStatuses" to "service_role";

grant references on table "public"."UserStatuses" to "service_role";

grant select on table "public"."UserStatuses" to "service_role";

grant trigger on table "public"."UserStatuses" to "service_role";

grant truncate on table "public"."UserStatuses" to "service_role";

grant update on table "public"."UserStatuses" to "service_role";

grant delete on table "public"."Users" to "anon";

grant insert on table "public"."Users" to "anon";

grant references on table "public"."Users" to "anon";

grant select on table "public"."Users" to "anon";

grant trigger on table "public"."Users" to "anon";

grant truncate on table "public"."Users" to "anon";

grant update on table "public"."Users" to "anon";

grant delete on table "public"."Users" to "authenticated";

grant insert on table "public"."Users" to "authenticated";

grant references on table "public"."Users" to "authenticated";

grant select on table "public"."Users" to "authenticated";

grant trigger on table "public"."Users" to "authenticated";

grant truncate on table "public"."Users" to "authenticated";

grant update on table "public"."Users" to "authenticated";

grant delete on table "public"."Users" to "service_role";

grant insert on table "public"."Users" to "service_role";

grant references on table "public"."Users" to "service_role";

grant select on table "public"."Users" to "service_role";

grant trigger on table "public"."Users" to "service_role";

grant truncate on table "public"."Users" to "service_role";

grant update on table "public"."Users" to "service_role";

grant delete on table "public"."WorkTrackers" to "anon";

grant insert on table "public"."WorkTrackers" to "anon";

grant references on table "public"."WorkTrackers" to "anon";

grant select on table "public"."WorkTrackers" to "anon";

grant trigger on table "public"."WorkTrackers" to "anon";

grant truncate on table "public"."WorkTrackers" to "anon";

grant update on table "public"."WorkTrackers" to "anon";

grant delete on table "public"."WorkTrackers" to "authenticated";

grant insert on table "public"."WorkTrackers" to "authenticated";

grant references on table "public"."WorkTrackers" to "authenticated";

grant select on table "public"."WorkTrackers" to "authenticated";

grant trigger on table "public"."WorkTrackers" to "authenticated";

grant truncate on table "public"."WorkTrackers" to "authenticated";

grant update on table "public"."WorkTrackers" to "authenticated";

grant delete on table "public"."WorkTrackers" to "service_role";

grant insert on table "public"."WorkTrackers" to "service_role";

grant references on table "public"."WorkTrackers" to "service_role";

grant select on table "public"."WorkTrackers" to "service_role";

grant trigger on table "public"."WorkTrackers" to "service_role";

grant truncate on table "public"."WorkTrackers" to "service_role";

grant update on table "public"."WorkTrackers" to "service_role";


  create policy "allow all for auth"
  on "public"."Addresses"
  as permissive
  for all
  to authenticated
using (true);



  create policy "allow all for auth"
  on "public"."BleacherEvents"
  as permissive
  for all
  to public
using (true);



  create policy "Allow All for Auth"
  on "public"."BleacherUsers"
  as permissive
  for all
  to authenticated
using (true);



  create policy "allow all for auth"
  on "public"."Bleachers"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow All for Auth"
  on "public"."Blocks"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow All for Auth"
  on "public"."Drivers"
  as permissive
  for all
  to authenticated
using (true);



  create policy "allow all for auth"
  on "public"."Events"
  as permissive
  for all
  to authenticated
using (true);



  create policy "allow all for auth"
  on "public"."HomeBases"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow All for Auth"
  on "public"."TaskStatuses"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow All for Auth"
  on "public"."TaskTypes"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow All for Auth"
  on "public"."Tasks"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow All for Auth"
  on "public"."UserHomeBases"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow All for Auth"
  on "public"."UserRoles"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allout All for Auth"
  on "public"."UserRolesJunction"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow All for Auth"
  on "public"."UserStatuses"
  as permissive
  for all
  to authenticated
using (true);



  create policy "allow all for auth"
  on "public"."Users"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Allow All for Auth"
  on "public"."WorkTrackers"
  as permissive
  for all
  to authenticated
using (true);



