create table public."HomeBases" (
  home_base_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  home_base_name text not null,
  constraint HomeBases_pkey primary key (home_base_id)
);

ALTER TABLE "public"."HomeBases" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow all for auth" ON "public"."HomeBases" TO "authenticated" USING (true);