create table "public"."UserHomeBases" (
    "user_home_base_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "home_base_id" bigint
);


alter table "public"."UserHomeBases" enable row level security;

create table "public"."UserRoles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role" text not null
);


alter table "public"."UserRoles" enable row level security;

create table "public"."UserStatuses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "status" text not null
);


alter table "public"."UserStatuses" enable row level security;

alter table "public"."Users" add column "avatar_image_url" text;

alter table "public"."Users" add column "role" bigint default 1;

alter table "public"."Users" add column "status" bigint not null default 1;

CREATE UNIQUE INDEX userhomebases_pkey ON public."UserHomeBases" USING btree (user_home_base_id);

CREATE UNIQUE INDEX userroles_pkey ON public."UserRoles" USING btree (id);

CREATE UNIQUE INDEX userstatuses_pkey ON public."UserStatuses" USING btree (id);

alter table "public"."UserHomeBases" add constraint "userhomebases_pkey" PRIMARY KEY using index "userhomebases_pkey";

alter table "public"."UserRoles" add constraint "userroles_pkey" PRIMARY KEY using index "userroles_pkey";

alter table "public"."UserStatuses" add constraint "userstatuses_pkey" PRIMARY KEY using index "userstatuses_pkey";

alter table "public"."UserHomeBases" add constraint "userhomebases_home_base_id_fkey" FOREIGN KEY (home_base_id) REFERENCES "HomeBases"(home_base_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."UserHomeBases" validate constraint "userhomebases_home_base_id_fkey";

alter table "public"."UserHomeBases" add constraint "userhomebases_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "Users"(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."UserHomeBases" validate constraint "userhomebases_user_id_fkey";

grant delete on table "public"."UserHomeBases" to "anon";

grant insert on table "public"."UserHomeBases" to "anon";

grant references on table "public"."UserHomeBases" to "anon";

grant select on table "public"."UserHomeBases" to "anon";

grant trigger on table "public"."UserHomeBases" to "anon";

grant truncate on table "public"."UserHomeBases" to "anon";

grant update on table "public"."UserHomeBases" to "anon";

grant delete on table "public"."UserHomeBases" to "authenticated";

grant insert on table "public"."UserHomeBases" to "authenticated";

grant references on table "public"."UserHomeBases" to "authenticated";

grant select on table "public"."UserHomeBases" to "authenticated";

grant trigger on table "public"."UserHomeBases" to "authenticated";

grant truncate on table "public"."UserHomeBases" to "authenticated";

grant update on table "public"."UserHomeBases" to "authenticated";

grant delete on table "public"."UserHomeBases" to "service_role";

grant insert on table "public"."UserHomeBases" to "service_role";

grant references on table "public"."UserHomeBases" to "service_role";

grant select on table "public"."UserHomeBases" to "service_role";

grant trigger on table "public"."UserHomeBases" to "service_role";

grant truncate on table "public"."UserHomeBases" to "service_role";

grant update on table "public"."UserHomeBases" to "service_role";

grant delete on table "public"."UserRoles" to "anon";

grant insert on table "public"."UserRoles" to "anon";

grant references on table "public"."UserRoles" to "anon";

grant select on table "public"."UserRoles" to "anon";

grant trigger on table "public"."UserRoles" to "anon";

grant truncate on table "public"."UserRoles" to "anon";

grant update on table "public"."UserRoles" to "anon";

grant delete on table "public"."UserRoles" to "authenticated";

grant insert on table "public"."UserRoles" to "authenticated";

grant references on table "public"."UserRoles" to "authenticated";

grant select on table "public"."UserRoles" to "authenticated";

grant trigger on table "public"."UserRoles" to "authenticated";

grant truncate on table "public"."UserRoles" to "authenticated";

grant update on table "public"."UserRoles" to "authenticated";

grant delete on table "public"."UserRoles" to "service_role";

grant insert on table "public"."UserRoles" to "service_role";

grant references on table "public"."UserRoles" to "service_role";

grant select on table "public"."UserRoles" to "service_role";

grant trigger on table "public"."UserRoles" to "service_role";

grant truncate on table "public"."UserRoles" to "service_role";

grant update on table "public"."UserRoles" to "service_role";

grant delete on table "public"."UserStatuses" to "anon";

grant insert on table "public"."UserStatuses" to "anon";

grant references on table "public"."UserStatuses" to "anon";

grant select on table "public"."UserStatuses" to "anon";

grant trigger on table "public"."UserStatuses" to "anon";

grant truncate on table "public"."UserStatuses" to "anon";

grant update on table "public"."UserStatuses" to "anon";

grant delete on table "public"."UserStatuses" to "authenticated";

grant insert on table "public"."UserStatuses" to "authenticated";

grant references on table "public"."UserStatuses" to "authenticated";

grant select on table "public"."UserStatuses" to "authenticated";

grant trigger on table "public"."UserStatuses" to "authenticated";

grant truncate on table "public"."UserStatuses" to "authenticated";

grant update on table "public"."UserStatuses" to "authenticated";

grant delete on table "public"."UserStatuses" to "service_role";

grant insert on table "public"."UserStatuses" to "service_role";

grant references on table "public"."UserStatuses" to "service_role";

grant select on table "public"."UserStatuses" to "service_role";

grant trigger on table "public"."UserStatuses" to "service_role";

grant truncate on table "public"."UserStatuses" to "service_role";

grant update on table "public"."UserStatuses" to "service_role";

create policy "Allow All for Auth"
on "public"."UserHomeBases"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."UserRoles"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."UserStatuses"
as permissive
for all
to authenticated
using (true);



