

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Addresses" (
    "address_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "street" "text" NOT NULL,
    "city" "text" NOT NULL,
    "state_province" "text" NOT NULL,
    "zip_postal" "text"
);


ALTER TABLE "public"."Addresses" OWNER TO "postgres";


ALTER TABLE "public"."Addresses" ALTER COLUMN "address_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Addresses_address_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."BleacherEvents" (
    "bleacher_event_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "bleacher_id" bigint NOT NULL,
    "event_id" bigint NOT NULL
);


ALTER TABLE "public"."BleacherEvents" OWNER TO "postgres";


ALTER TABLE "public"."BleacherEvents" ALTER COLUMN "bleacher_event_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."BleacherEvents_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Bleachers" (
    "bleacher_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text") NOT NULL,
    "bleacher_number" smallint NOT NULL,
    "home_base_id" bigint NOT NULL,
    "winter_home_base_id" bigint NOT NULL,
    "bleacher_rows" smallint NOT NULL,
    "bleacher_seats" smallint NOT NULL,
    "created_by" "uuid",
    "updated_at" timestamp without time zone,
    "updated_by" "uuid"
);

ALTER TABLE ONLY "public"."Bleachers" REPLICA IDENTITY FULL;


ALTER TABLE "public"."Bleachers" OWNER TO "postgres";


ALTER TABLE "public"."Bleachers" ALTER COLUMN "bleacher_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Bleachers_bleacher_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Events" (
    "event_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event_name" "text" NOT NULL,
    "setup_start" "date",
    "event_start" "date" NOT NULL,
    "event_end" "date" NOT NULL,
    "teardown_end" "date",
    "address_id" bigint NOT NULL,
    "total_seats" integer,
    "seven_row" smallint,
    "ten_row" smallint,
    "fifteen_row" smallint,
    "lenient" boolean NOT NULL,
    "booked" boolean DEFAULT false NOT NULL,
    "notes" "text",
    "must_be_clean" boolean DEFAULT false NOT NULL,
    "hsl_hue" smallint
);


ALTER TABLE "public"."Events" OWNER TO "postgres";


ALTER TABLE "public"."Events" ALTER COLUMN "event_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."HomeBases" (
    "home_base_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "home_base_name" "text" NOT NULL
);


ALTER TABLE "public"."HomeBases" OWNER TO "postgres";


ALTER TABLE "public"."HomeBases" ALTER COLUMN "home_base_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."HomeBases_home_base_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."InvitedUsers" (
    "invited_user_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text" NOT NULL
);


ALTER TABLE "public"."InvitedUsers" OWNER TO "postgres";


ALTER TABLE "public"."InvitedUsers" ALTER COLUMN "invited_user_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."InvitedUsers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Users" (
    "user_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "email" "text" NOT NULL,
    "phone" "text",
    "clerk_user_id" "text"
);


ALTER TABLE "public"."Users" OWNER TO "postgres";


ALTER TABLE "public"."Users" ALTER COLUMN "user_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Users_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Addresses"
    ADD CONSTRAINT "Addresses_pkey" PRIMARY KEY ("address_id");



ALTER TABLE ONLY "public"."BleacherEvents"
    ADD CONSTRAINT "BleacherEvents_pkey" PRIMARY KEY ("bleacher_event_id");



ALTER TABLE ONLY "public"."Bleachers"
    ADD CONSTRAINT "Bleachers_bleacher_number_key" UNIQUE ("bleacher_number");



ALTER TABLE ONLY "public"."Bleachers"
    ADD CONSTRAINT "Bleachers_pkey" PRIMARY KEY ("bleacher_id");



ALTER TABLE ONLY "public"."Events"
    ADD CONSTRAINT "Events_pkey" PRIMARY KEY ("event_id");



ALTER TABLE ONLY "public"."HomeBases"
    ADD CONSTRAINT "HomeBases_pkey" PRIMARY KEY ("home_base_id");



ALTER TABLE ONLY "public"."InvitedUsers"
    ADD CONSTRAINT "InvitedUsers_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."InvitedUsers"
    ADD CONSTRAINT "InvitedUsers_pkey" PRIMARY KEY ("invited_user_id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_clerk_user_id_key" UNIQUE ("clerk_user_id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."BleacherEvents"
    ADD CONSTRAINT "BleacherEvents_bleacher_id_fkey" FOREIGN KEY ("bleacher_id") REFERENCES "public"."Bleachers"("bleacher_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."BleacherEvents"
    ADD CONSTRAINT "BleacherEvents_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."Events"("event_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Bleachers"
    ADD CONSTRAINT "Bleachers_home_base_id_fkey" FOREIGN KEY ("home_base_id") REFERENCES "public"."HomeBases"("home_base_id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."Bleachers"
    ADD CONSTRAINT "Bleachers_winter_home_base_id_fkey" FOREIGN KEY ("winter_home_base_id") REFERENCES "public"."HomeBases"("home_base_id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."Events"
    ADD CONSTRAINT "Events_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."Addresses"("address_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE "public"."Addresses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."BleacherEvents" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Bleachers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."HomeBases" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."InvitedUsers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Users" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "allow all for auth" ON "public"."Addresses" TO "authenticated" USING (true);



CREATE POLICY "allow all for auth" ON "public"."BleacherEvents" USING (true);



CREATE POLICY "allow all for auth" ON "public"."Bleachers" TO "authenticated" USING (true);



CREATE POLICY "allow all for auth" ON "public"."Events" TO "authenticated" USING (true);



CREATE POLICY "allow all for auth" ON "public"."HomeBases" TO "authenticated" USING (true);



CREATE POLICY "allow all for auth" ON "public"."InvitedUsers" TO "authenticated" USING (true);



CREATE POLICY "allow all for auth" ON "public"."Users" TO "authenticated" USING (true);



CREATE POLICY "select auth" ON "public"."Users" FOR SELECT TO "authenticated" USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Addresses";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."BleacherEvents";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Bleachers";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Events";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."HomeBases";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."InvitedUsers";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Users";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."Addresses" TO "anon";
GRANT ALL ON TABLE "public"."Addresses" TO "authenticated";
GRANT ALL ON TABLE "public"."Addresses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Addresses_address_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Addresses_address_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Addresses_address_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."BleacherEvents" TO "anon";
GRANT ALL ON TABLE "public"."BleacherEvents" TO "authenticated";
GRANT ALL ON TABLE "public"."BleacherEvents" TO "service_role";



GRANT ALL ON SEQUENCE "public"."BleacherEvents_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."BleacherEvents_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."BleacherEvents_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Bleachers" TO "anon";
GRANT ALL ON TABLE "public"."Bleachers" TO "authenticated";
GRANT ALL ON TABLE "public"."Bleachers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Bleachers_bleacher_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Bleachers_bleacher_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Bleachers_bleacher_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Events" TO "anon";
GRANT ALL ON TABLE "public"."Events" TO "authenticated";
GRANT ALL ON TABLE "public"."Events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."HomeBases" TO "anon";
GRANT ALL ON TABLE "public"."HomeBases" TO "authenticated";
GRANT ALL ON TABLE "public"."HomeBases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."HomeBases_home_base_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."HomeBases_home_base_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."HomeBases_home_base_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."InvitedUsers" TO "anon";
GRANT ALL ON TABLE "public"."InvitedUsers" TO "authenticated";
GRANT ALL ON TABLE "public"."InvitedUsers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."InvitedUsers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."InvitedUsers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."InvitedUsers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Users" TO "anon";
GRANT ALL ON TABLE "public"."Users" TO "authenticated";
GRANT ALL ON TABLE "public"."Users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Users_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Users_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Users_user_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
