create table "public"."addresses" (
    "address_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "street" text not null,
    "city" text not null,
    "state_province" text not null,
    "zip_postal" text
);


create table "public"."bleacherevents" (
    "bleacher_event_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "bleacher_id" bigint not null,
    "event_id" bigint not null
);


create table "public"."bleachers" (
    "bleacher_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "bleacher_number" smallint not null,
    "home_base_id" bigint not null,
    "winter_home_base_id" bigint not null,
    "bleacher_rows" smallint not null,
    "bleacher_seats" smallint not null,
    "created_by" uuid,
    "updated_at" timestamp without time zone,
    "updated_by" uuid
);


create table "public"."events" (
    "event_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_name" text not null,
    "setup_start" date,
    "event_start" date not null,
    "event_end" date not null,
    "teardown_end" date,
    "address_id" bigint not null,
    "total_seats" integer,
    "seven_row" smallint,
    "ten_row" smallint,
    "fifteen_row" smallint,
    "lenient" boolean not null,
    "booked" boolean not null default false,
    "notes" text,
    "must_be_clean" boolean not null default false,
    "hsl_hue" smallint
);


create table "public"."homebases" (
    "home_base_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "home_base_name" text not null
);


create table "public"."userhomebases" (
    "user_home_base_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "home_base_id" bigint
);


create table "public"."userroles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role" text not null
);


create table "public"."users" (
    "user_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text,
    "last_name" text,
    "email" text not null,
    "phone" text,
    "clerk_user_id" text,
    "status" bigint not null default '1'::bigint,
    "role" bigint default '1'::bigint
);


create table "public"."userstatuses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "status" text not null
);


CREATE UNIQUE INDEX addresses_pkey ON public.addresses USING btree (address_id);

CREATE UNIQUE INDEX bleacherevents_pkey ON public.bleacherevents USING btree (bleacher_event_id);

CREATE UNIQUE INDEX bleachers_bleacher_number_key ON public.bleachers USING btree (bleacher_number);

CREATE UNIQUE INDEX bleachers_pkey ON public.bleachers USING btree (bleacher_id);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (event_id);

CREATE UNIQUE INDEX homebases_pkey ON public.homebases USING btree (home_base_id);

CREATE UNIQUE INDEX userhomebases_pkey ON public.userhomebases USING btree (user_home_base_id);

CREATE UNIQUE INDEX userroles_pkey ON public.userroles USING btree (id);

CREATE UNIQUE INDEX users_clerk_user_id_key ON public.users USING btree (clerk_user_id);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (user_id);

CREATE UNIQUE INDEX userstatuses_pkey ON public.userstatuses USING btree (id);

alter table "public"."addresses" add constraint "addresses_pkey" PRIMARY KEY using index "addresses_pkey";

alter table "public"."bleacherevents" add constraint "bleacherevents_pkey" PRIMARY KEY using index "bleacherevents_pkey";

alter table "public"."bleachers" add constraint "bleachers_pkey" PRIMARY KEY using index "bleachers_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."homebases" add constraint "homebases_pkey" PRIMARY KEY using index "homebases_pkey";

alter table "public"."userhomebases" add constraint "userhomebases_pkey" PRIMARY KEY using index "userhomebases_pkey";

alter table "public"."userroles" add constraint "userroles_pkey" PRIMARY KEY using index "userroles_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."userstatuses" add constraint "userstatuses_pkey" PRIMARY KEY using index "userstatuses_pkey";

alter table "public"."bleacherevents" add constraint "bleacherevents_bleacher_id_fkey" FOREIGN KEY (bleacher_id) REFERENCES bleachers(bleacher_id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."bleacherevents" validate constraint "bleacherevents_bleacher_id_fkey";

alter table "public"."bleacherevents" add constraint "bleacherevents_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(event_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."bleacherevents" validate constraint "bleacherevents_event_id_fkey";

alter table "public"."bleachers" add constraint "bleachers_bleacher_number_key" UNIQUE using index "bleachers_bleacher_number_key";

alter table "public"."bleachers" add constraint "bleachers_home_base_id_fkey" FOREIGN KEY (home_base_id) REFERENCES homebases(home_base_id) ON UPDATE CASCADE not valid;

alter table "public"."bleachers" validate constraint "bleachers_home_base_id_fkey";

alter table "public"."bleachers" add constraint "bleachers_winter_home_base_id_fkey" FOREIGN KEY (winter_home_base_id) REFERENCES homebases(home_base_id) ON UPDATE CASCADE not valid;

alter table "public"."bleachers" validate constraint "bleachers_winter_home_base_id_fkey";

alter table "public"."events" add constraint "events_address_id_fkey" FOREIGN KEY (address_id) REFERENCES addresses(address_id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."events" validate constraint "events_address_id_fkey";

alter table "public"."userhomebases" add constraint "userhomebases_home_base_id_fkey" FOREIGN KEY (home_base_id) REFERENCES homebases(home_base_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."userhomebases" validate constraint "userhomebases_home_base_id_fkey";

alter table "public"."userhomebases" add constraint "userhomebases_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."userhomebases" validate constraint "userhomebases_user_id_fkey";

alter table "public"."users" add constraint "users_clerk_user_id_key" UNIQUE using index "users_clerk_user_id_key";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

grant delete on table "public"."addresses" to "anon";

grant insert on table "public"."addresses" to "anon";

grant references on table "public"."addresses" to "anon";

grant select on table "public"."addresses" to "anon";

grant trigger on table "public"."addresses" to "anon";

grant truncate on table "public"."addresses" to "anon";

grant update on table "public"."addresses" to "anon";

grant delete on table "public"."addresses" to "authenticated";

grant insert on table "public"."addresses" to "authenticated";

grant references on table "public"."addresses" to "authenticated";

grant select on table "public"."addresses" to "authenticated";

grant trigger on table "public"."addresses" to "authenticated";

grant truncate on table "public"."addresses" to "authenticated";

grant update on table "public"."addresses" to "authenticated";

grant delete on table "public"."addresses" to "service_role";

grant insert on table "public"."addresses" to "service_role";

grant references on table "public"."addresses" to "service_role";

grant select on table "public"."addresses" to "service_role";

grant trigger on table "public"."addresses" to "service_role";

grant truncate on table "public"."addresses" to "service_role";

grant update on table "public"."addresses" to "service_role";

grant delete on table "public"."bleacherevents" to "anon";

grant insert on table "public"."bleacherevents" to "anon";

grant references on table "public"."bleacherevents" to "anon";

grant select on table "public"."bleacherevents" to "anon";

grant trigger on table "public"."bleacherevents" to "anon";

grant truncate on table "public"."bleacherevents" to "anon";

grant update on table "public"."bleacherevents" to "anon";

grant delete on table "public"."bleacherevents" to "authenticated";

grant insert on table "public"."bleacherevents" to "authenticated";

grant references on table "public"."bleacherevents" to "authenticated";

grant select on table "public"."bleacherevents" to "authenticated";

grant trigger on table "public"."bleacherevents" to "authenticated";

grant truncate on table "public"."bleacherevents" to "authenticated";

grant update on table "public"."bleacherevents" to "authenticated";

grant delete on table "public"."bleacherevents" to "service_role";

grant insert on table "public"."bleacherevents" to "service_role";

grant references on table "public"."bleacherevents" to "service_role";

grant select on table "public"."bleacherevents" to "service_role";

grant trigger on table "public"."bleacherevents" to "service_role";

grant truncate on table "public"."bleacherevents" to "service_role";

grant update on table "public"."bleacherevents" to "service_role";

grant delete on table "public"."bleachers" to "anon";

grant insert on table "public"."bleachers" to "anon";

grant references on table "public"."bleachers" to "anon";

grant select on table "public"."bleachers" to "anon";

grant trigger on table "public"."bleachers" to "anon";

grant truncate on table "public"."bleachers" to "anon";

grant update on table "public"."bleachers" to "anon";

grant delete on table "public"."bleachers" to "authenticated";

grant insert on table "public"."bleachers" to "authenticated";

grant references on table "public"."bleachers" to "authenticated";

grant select on table "public"."bleachers" to "authenticated";

grant trigger on table "public"."bleachers" to "authenticated";

grant truncate on table "public"."bleachers" to "authenticated";

grant update on table "public"."bleachers" to "authenticated";

grant delete on table "public"."bleachers" to "service_role";

grant insert on table "public"."bleachers" to "service_role";

grant references on table "public"."bleachers" to "service_role";

grant select on table "public"."bleachers" to "service_role";

grant trigger on table "public"."bleachers" to "service_role";

grant truncate on table "public"."bleachers" to "service_role";

grant update on table "public"."bleachers" to "service_role";

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";

grant delete on table "public"."homebases" to "anon";

grant insert on table "public"."homebases" to "anon";

grant references on table "public"."homebases" to "anon";

grant select on table "public"."homebases" to "anon";

grant trigger on table "public"."homebases" to "anon";

grant truncate on table "public"."homebases" to "anon";

grant update on table "public"."homebases" to "anon";

grant delete on table "public"."homebases" to "authenticated";

grant insert on table "public"."homebases" to "authenticated";

grant references on table "public"."homebases" to "authenticated";

grant select on table "public"."homebases" to "authenticated";

grant trigger on table "public"."homebases" to "authenticated";

grant truncate on table "public"."homebases" to "authenticated";

grant update on table "public"."homebases" to "authenticated";

grant delete on table "public"."homebases" to "service_role";

grant insert on table "public"."homebases" to "service_role";

grant references on table "public"."homebases" to "service_role";

grant select on table "public"."homebases" to "service_role";

grant trigger on table "public"."homebases" to "service_role";

grant truncate on table "public"."homebases" to "service_role";

grant update on table "public"."homebases" to "service_role";

grant delete on table "public"."userhomebases" to "anon";

grant insert on table "public"."userhomebases" to "anon";

grant references on table "public"."userhomebases" to "anon";

grant select on table "public"."userhomebases" to "anon";

grant trigger on table "public"."userhomebases" to "anon";

grant truncate on table "public"."userhomebases" to "anon";

grant update on table "public"."userhomebases" to "anon";

grant delete on table "public"."userhomebases" to "authenticated";

grant insert on table "public"."userhomebases" to "authenticated";

grant references on table "public"."userhomebases" to "authenticated";

grant select on table "public"."userhomebases" to "authenticated";

grant trigger on table "public"."userhomebases" to "authenticated";

grant truncate on table "public"."userhomebases" to "authenticated";

grant update on table "public"."userhomebases" to "authenticated";

grant delete on table "public"."userhomebases" to "service_role";

grant insert on table "public"."userhomebases" to "service_role";

grant references on table "public"."userhomebases" to "service_role";

grant select on table "public"."userhomebases" to "service_role";

grant trigger on table "public"."userhomebases" to "service_role";

grant truncate on table "public"."userhomebases" to "service_role";

grant update on table "public"."userhomebases" to "service_role";

grant delete on table "public"."userroles" to "anon";

grant insert on table "public"."userroles" to "anon";

grant references on table "public"."userroles" to "anon";

grant select on table "public"."userroles" to "anon";

grant trigger on table "public"."userroles" to "anon";

grant truncate on table "public"."userroles" to "anon";

grant update on table "public"."userroles" to "anon";

grant delete on table "public"."userroles" to "authenticated";

grant insert on table "public"."userroles" to "authenticated";

grant references on table "public"."userroles" to "authenticated";

grant select on table "public"."userroles" to "authenticated";

grant trigger on table "public"."userroles" to "authenticated";

grant truncate on table "public"."userroles" to "authenticated";

grant update on table "public"."userroles" to "authenticated";

grant delete on table "public"."userroles" to "service_role";

grant insert on table "public"."userroles" to "service_role";

grant references on table "public"."userroles" to "service_role";

grant select on table "public"."userroles" to "service_role";

grant trigger on table "public"."userroles" to "service_role";

grant truncate on table "public"."userroles" to "service_role";

grant update on table "public"."userroles" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."userstatuses" to "anon";

grant insert on table "public"."userstatuses" to "anon";

grant references on table "public"."userstatuses" to "anon";

grant select on table "public"."userstatuses" to "anon";

grant trigger on table "public"."userstatuses" to "anon";

grant truncate on table "public"."userstatuses" to "anon";

grant update on table "public"."userstatuses" to "anon";

grant delete on table "public"."userstatuses" to "authenticated";

grant insert on table "public"."userstatuses" to "authenticated";

grant references on table "public"."userstatuses" to "authenticated";

grant select on table "public"."userstatuses" to "authenticated";

grant trigger on table "public"."userstatuses" to "authenticated";

grant truncate on table "public"."userstatuses" to "authenticated";

grant update on table "public"."userstatuses" to "authenticated";

grant delete on table "public"."userstatuses" to "service_role";

grant insert on table "public"."userstatuses" to "service_role";

grant references on table "public"."userstatuses" to "service_role";

grant select on table "public"."userstatuses" to "service_role";

grant trigger on table "public"."userstatuses" to "service_role";

grant truncate on table "public"."userstatuses" to "service_role";

grant update on table "public"."userstatuses" to "service_role";

create policy "Allow All for Auth"
on "public"."addresses"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."bleacherevents"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."bleachers"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."events"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."homebases"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."userhomebases"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."userroles"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."users"
as permissive
for all
to authenticated
using (true);


create policy "Allow All for Auth"
on "public"."userstatuses"
as permissive
for all
to authenticated
using (true);



