create table "public"."TestTable" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "test_name" text,
    "bleacher_id" bigint
);


alter table "public"."TestTable" enable row level security;

CREATE UNIQUE INDEX "Test Table_pkey" ON public."TestTable" USING btree (id);

alter table "public"."TestTable" add constraint "Test Table_pkey" PRIMARY KEY using index "Test Table_pkey";

alter table "public"."TestTable" add constraint "Test Table_bleacher_id_fkey" FOREIGN KEY (bleacher_id) REFERENCES "Bleachers"(bleacher_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."TestTable" validate constraint "Test Table_bleacher_id_fkey";

grant delete on table "public"."TestTable" to "anon";

grant insert on table "public"."TestTable" to "anon";

grant references on table "public"."TestTable" to "anon";

grant select on table "public"."TestTable" to "anon";

grant trigger on table "public"."TestTable" to "anon";

grant truncate on table "public"."TestTable" to "anon";

grant update on table "public"."TestTable" to "anon";

grant delete on table "public"."TestTable" to "authenticated";

grant insert on table "public"."TestTable" to "authenticated";

grant references on table "public"."TestTable" to "authenticated";

grant select on table "public"."TestTable" to "authenticated";

grant trigger on table "public"."TestTable" to "authenticated";

grant truncate on table "public"."TestTable" to "authenticated";

grant update on table "public"."TestTable" to "authenticated";

grant delete on table "public"."TestTable" to "service_role";

grant insert on table "public"."TestTable" to "service_role";

grant references on table "public"."TestTable" to "service_role";

grant select on table "public"."TestTable" to "service_role";

grant trigger on table "public"."TestTable" to "service_role";

grant truncate on table "public"."TestTable" to "service_role";

grant update on table "public"."TestTable" to "service_role";


