create table "public"."Blocks" (
    "block_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "bleacher_id" bigint,
    "text" text,
    "date" date
);


alter table "public"."Blocks" enable row level security;

CREATE UNIQUE INDEX "Block_pkey" ON public."Blocks" USING btree (block_id);

alter table "public"."Blocks" add constraint "Block_pkey" PRIMARY KEY using index "Block_pkey";

alter table "public"."Blocks" add constraint "Block_bleacher_id_fkey" FOREIGN KEY (bleacher_id) REFERENCES "Bleachers"(bleacher_id) not valid;

alter table "public"."Blocks" validate constraint "Block_bleacher_id_fkey";

grant delete on table "public"."Blocks" to "anon";

grant insert on table "public"."Blocks" to "anon";

grant references on table "public"."Blocks" to "anon";

grant select on table "public"."Blocks" to "anon";

grant trigger on table "public"."Blocks" to "anon";

grant truncate on table "public"."Blocks" to "anon";

grant update on table "public"."Blocks" to "anon";

grant delete on table "public"."Blocks" to "authenticated";

grant insert on table "public"."Blocks" to "authenticated";

grant references on table "public"."Blocks" to "authenticated";

grant select on table "public"."Blocks" to "authenticated";

grant trigger on table "public"."Blocks" to "authenticated";

grant truncate on table "public"."Blocks" to "authenticated";

grant update on table "public"."Blocks" to "authenticated";

grant delete on table "public"."Blocks" to "service_role";

grant insert on table "public"."Blocks" to "service_role";

grant references on table "public"."Blocks" to "service_role";

grant select on table "public"."Blocks" to "service_role";

grant trigger on table "public"."Blocks" to "service_role";

grant truncate on table "public"."Blocks" to "service_role";

grant update on table "public"."Blocks" to "service_role";

create policy "Allow All for Auth"
on "public"."Blocks"
as permissive
for all
to authenticated
using (true);



