
  create table "public"."TestTable" (
    "test_table_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "entry" text not null
      );


alter table "public"."TestTable" enable row level security;

CREATE UNIQUE INDEX "TestTable_pkey" ON public."TestTable" USING btree (test_table_id);

alter table "public"."TestTable" add constraint "TestTable_pkey" PRIMARY KEY using index "TestTable_pkey";

grant delete on table "public"."TestTable" to "anon";

grant insert on table "public"."TestTable" to "anon";

grant references on table "public"."TestTable" to "anon";

grant select on table "public"."TestTable" to "anon";

grant trigger on table "public"."TestTable" to "anon";

grant truncate on table "public"."TestTable" to "anon";

grant update on table "public"."TestTable" to "anon";

grant delete on table "public"."TestTable" to "authenticated";

grant insert on table "public"."TestTable" to "authenticated";

grant references on table "public"."TestTable" to "authenticated";

grant select on table "public"."TestTable" to "authenticated";

grant trigger on table "public"."TestTable" to "authenticated";

grant truncate on table "public"."TestTable" to "authenticated";

grant update on table "public"."TestTable" to "authenticated";

grant delete on table "public"."TestTable" to "postgres";

grant insert on table "public"."TestTable" to "postgres";

grant references on table "public"."TestTable" to "postgres";

grant select on table "public"."TestTable" to "postgres";

grant trigger on table "public"."TestTable" to "postgres";

grant truncate on table "public"."TestTable" to "postgres";

grant update on table "public"."TestTable" to "postgres";

grant delete on table "public"."TestTable" to "service_role";

grant insert on table "public"."TestTable" to "service_role";

grant references on table "public"."TestTable" to "service_role";

grant select on table "public"."TestTable" to "service_role";

grant trigger on table "public"."TestTable" to "service_role";

grant truncate on table "public"."TestTable" to "service_role";

grant update on table "public"."TestTable" to "service_role";


  create policy "Allow All for Auth"
  on "public"."TestTable"
  as permissive
  for all
  to authenticated
using (true);



