create table public."Addresses" (
  address_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  street text not null,
  city text not null,
  state_province text not null,
  zip_postal text null,
  constraint Addresses_pkey primary key (address_id)
);
ALTER TABLE "public"."Addresses" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow all for auth" ON "public"."Addresses" TO "authenticated" USING (true);