create table public."Bleachers" (
  bleacher_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  bleacher_number smallint not null,
  home_base_id bigint not null,
  winter_home_base_id bigint not null,
  bleacher_rows smallint not null,
  bleacher_seats smallint not null,
  created_by uuid null,
  updated_at timestamp without time zone null,
  updated_by uuid null,
  linxup_device_id text null,
  constraint Bleachers_pkey primary key (bleacher_id),
  constraint Bleachers_bleacher_number_key unique (bleacher_number),
  constraint Bleachers_linxup_device_id_key unique (linxup_device_id),
  constraint Bleachers_home_base_id_fkey foreign KEY (home_base_id) references "HomeBases" (home_base_id) on update CASCADE,
  constraint Bleachers_winter_home_base_id_fkey foreign KEY (winter_home_base_id) references "HomeBases" (home_base_id) on update CASCADE
);

ALTER TABLE "public"."Bleachers" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow all for auth" ON "public"."Bleachers" TO "authenticated";