-- ============================================================================
-- Direct Line to Developers — authorship notices on a driver's backlog ticket.
--
-- Follows 20260826120000_driver_backlog_tickets.sql. That migration let drivers
-- file, correct and withdraw their own `RoadmapTasks` rows; this one lets the
-- app say WHO did it, in the one place the web roadmap actually renders.
--
-- WHY THIS EXISTS AT ALL
--
-- `RoadmapTasks.created_by_user_uuid` has carried the answer since day one, but
-- the board shows a task's title, body and message thread — not its foreign
-- keys. A ticket filed from a phone therefore read as though it had written
-- itself, and an edit or a withdrawal was an unexplained event: a title that
-- mutated under whoever was reading it, or a ticket that simply went quiet.
-- The driver app now posts one `is_system` message per action — created,
-- edited, withdrawn — in the SAME local transaction as the change itself.
--
-- WHAT THE APP IS ALLOWED TO WRITE HERE, AND NOTHING MORE
--
-- One narrow permissive lane, ORed with the existing rbac_* policies on this
-- table (see 20260513153019_role_accessibility_policy.sql §2h), which are left
-- exactly as they were:
--
--   * the message must be `is_system` — a note on the board, never a reply in
--     the developers' conversation. Drivers have no reply UI, by product
--     decision: they are never shown ticket status, so a thread they could
--     write into would imply an answer that is not coming.
--   * it must be attributed to the driver writing it, and
--   * it must hang off a backlog ticket that same driver created.
--
-- NO TIME WINDOW ON THIS POLICY, DELIBERATELY
--
-- The ticket policies are bounded to 48h; this one is not, and must not be.
-- A withdrawal made offline at 47h59m carries its notice with it, and the two
-- rows arrive together — a window here could refuse the notice while accepting
-- the change it explains, which is the worse of the two outcomes. PowerSync
-- treats an RLS refusal (42501) as FATAL and drops the operation from its
-- upload queue in silence, so anything stricter than the client is a write
-- nobody is ever told about. The lane stays cheap for other reasons: a driver
-- may file only 3 tickets per rolling 24 hours, and each notice is one short
-- machine-written sentence about a row that is already theirs.
-- ============================================================================

drop policy if exists "driver_backlog_notice_insert" on public."RoadmapTaskMessages";
create policy "driver_backlog_notice_insert" on public."RoadmapTaskMessages"
  as permissive for insert to authenticated
  with check (
    public.get_current_driver_id() is not null
    and is_system
    and user_uuid = public.get_current_user_uuid()
    and exists (
      select 1
      from public."RoadmapTasks" t
      where t.id = task_id
        and t.is_backlog
        and t.created_by_user_uuid = public.get_current_user_uuid()
    )
  );

-- SELECT is required, and is not the widening it looks like.
--
-- PowerSync uploads through PostgREST, which asks for the inserted row back
-- (`Prefer: return=representation`) — so the statement is INSERT ... RETURNING.
-- Postgres applies SELECT policies to the returned row, and with none present
-- the whole insert fails with 42501, the same fatal code an actual permission
-- failure raises: the ticket committed, the notice was dropped from the upload
-- queue, and nobody was told. This mirrors the mobile sync stream exactly (only
-- the driver's own `is_system` notices on their own backlog tickets), so the
-- developers' conversation stays off the phone either way.

drop policy if exists "driver_backlog_notice_select" on public."RoadmapTaskMessages";
create policy "driver_backlog_notice_select" on public."RoadmapTaskMessages"
  as permissive for select to authenticated
  using (
    is_system
    and user_uuid = public.get_current_user_uuid()
    and exists (
      select 1
      from public."RoadmapTasks" t
      where t.id = task_id
        and t.is_backlog
        and t.created_by_user_uuid = public.get_current_user_uuid()
    )
  );

-- No update or delete policy for drivers, on purpose: a notice is a record of
-- something that happened, not the driver's to rewrite afterwards.

-- ── Guard trigger ───────────────────────────────────────────────────────────
--
-- The policy pins who and where; this pins the shape of the text. A notice is
-- generated by the app, not typed by anyone, so a body that is empty or the
-- size of a paragraph means the write did not come from the app — and the
-- board renders these inline, where a long one would bury the conversation.
--
-- The cap is generous rather than tight: the sentence carries a full name, an
-- email and a phone number, and a rejection here is a write PowerSync drops
-- without telling the driver. Being looser than the client is always the safe
-- direction; being stricter is the one failure this feature cannot afford.

create or replace function public.enforce_driver_backlog_notice()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Roadmap-side roles manage this table exactly as before.
  if public.get_user_roles() && '{admin,developer,account_manager}'::text[] then
    return new;
  end if;

  if public.get_current_driver_id() is null then
    return new;
  end if;

  if length(btrim(new.body)) = 0 then
    raise exception 'A backlog ticket notice cannot be empty'
      using errcode = 'check_violation';
  end if;

  if length(new.body) > 1000 then
    raise exception 'A backlog ticket notice is one sentence, not a message'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_driver_backlog_notice on public."RoadmapTaskMessages";
create trigger enforce_driver_backlog_notice
  before insert on public."RoadmapTaskMessages"
  for each row
  execute function public.enforce_driver_backlog_notice();

comment on function public.enforce_driver_backlog_notice() is
  'Driver-only guard on RoadmapTaskMessages: a notice written from the driver app '
  'must be one non-empty sentence (<= 1000 chars). Who may write one, and on which '
  'ticket, is the driver_backlog_notice_insert policy. Roadmap-side roles pass '
  'straight through.';
