name: Sync STAGING from PROD and Apply DEV Schema

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
      STAGING_DB_URL: ${{ secrets.STAGING_DB_URL }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_TPI }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase-linux-amd64 -o supabase
          chmod +x supabase
          sudo mv supabase /usr/local/bin

      - name: Dump PROD schema
        run: |
          pg_dump --schema-only --no-owner --dbname="$PROD_DB_URL" > prod_schema.sql

      - name: Dump PROD data
        run: |
          pg_dump --data-only --no-owner --dbname="$PROD_DB_URL" > prod_data.sql

      - name: Reset STAGING
        run: |
          psql "$STAGING_DB_URL" -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

      - name: Restore schema to STAGING
        run: |
          psql "$STAGING_DB_URL" < prod_schema.sql

      - name: Restore data to STAGING
        run: |
          psql "$STAGING_DB_URL" < prod_data.sql

      - name: Link and Push DEV Schema to STAGING
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push --db-url "$STAGING_DB_URL"
